# Setup
title:        Anderson Fortaleza
tagline:      Programming computers for fun and profit
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Anderson Fortaleza
  url:        http://afortaleza.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown